- name: Install rsync
  ansible.builtin.apt:
    name: rsync
    state: present
    update_cache: true

- name: Deploy each service
  ansible.builtin.include_tasks:
    file: deploy_service.yml
  loop: "{{ service_names }}"
  loop_control:
    loop_var: service
